"""
ParFlow Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the ParFlow integrated hydrologic model.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations in ParFlowConfig.
"""

from typing import Any, Dict

from symfluence.core.config.models.model_configs import ParFlowConfig
from symfluence.models.base import AutoGeneratedConfigAdapter


class ParFlowConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for ParFlow with auto-generated defaults and transformers.

    Defaults and transformers are automatically extracted from ParFlowConfig
    Pydantic model. Custom validation checks ParFlow-specific constraints.
    """

    def __init__(self, model_name: str = 'PARFLOW'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return ParFlow Pydantic configuration schema."""
        return ParFlowConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate ParFlow-specific configuration."""
        top = config.get('top', 1500.0)
        bot = config.get('bot', 1400.0)
        if top <= bot:
            raise ValueError(
                f"ParFlow top ({top}) must be greater than bot ({bot}). "
                f"Top is the domain surface elevation, bot is the bottom."
            )

        vg_alpha = config.get('vg_alpha', 1.0)
        if vg_alpha <= 0:
            raise ValueError(
                f"ParFlow vg_alpha ({vg_alpha}) must be positive."
            )

        vg_n = config.get('vg_n', 2.0)
        if vg_n <= 1.0:
            raise ValueError(
                f"ParFlow vg_n ({vg_n}) must be greater than 1.0."
            )

        s_res = config.get('s_res', 0.1)
        s_sat = config.get('s_sat', 1.0)
        if s_res >= s_sat:
            raise ValueError(
                f"ParFlow s_res ({s_res}) must be less than s_sat ({s_sat})."
            )
