"""
PRMS Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the PRMS model.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations in PRMSConfig.
"""

from typing import Any, Dict

from symfluence.core.config.models.model_configs import PRMSConfig
from symfluence.models.base import AutoGeneratedConfigAdapter


class PRMSConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for PRMS model with auto-generated defaults
    and transformers.

    Defaults and transformers are automatically extracted from PRMSConfig
    Pydantic model. Custom validation checks PRMS-specific constraints.
    """

    def __init__(self, model_name: str = 'PRMS'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return PRMS Pydantic configuration schema."""
        return PRMSConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate PRMS-specific configuration."""
        # Validate model mode
        mode = config.get('model_mode', 'DAILY')
        if mode not in ('DAILY', 'STORM', 'FROST'):
            raise ValueError(
                f"Invalid PRMS model_mode '{mode}'. "
                f"Must be 'DAILY', 'STORM', or 'FROST'."
            )
