"""Base classes for model preprocessors, runners, postprocessors, config adapters, and result extractors."""

from symfluence.core.exceptions import ConfigValidationError

from .base_config import AutoGeneratedConfigAdapter, ModelConfigAdapter, create_config_adapter
from .base_extractor import ModelResultExtractor
from .base_postprocessor import BaseModelPostProcessor
from .base_preprocessor import BaseModelPreProcessor
from .base_runner import BaseModelRunner
from .protocols import ModelPostProcessor, ModelPreProcessor, ModelRunner
from .standard_postprocessor import RoutedModelPostprocessor, StandardModelPostprocessor

__all__ = [
    'BaseModelPreProcessor',
    'BaseModelRunner',
    'BaseModelPostProcessor',
    'StandardModelPostprocessor',
    'RoutedModelPostprocessor',
    'ModelConfigAdapter',
    'AutoGeneratedConfigAdapter',
    'ConfigValidationError',
    'create_config_adapter',
    'ModelResultExtractor',
    'ModelRunner',
    'ModelPreProcessor',
    'ModelPostProcessor',
]
