"""
HydroGeoSphere Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the HydroGeoSphere (HGS) model.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations in HydroGeoSphereConfig.
"""

from typing import Dict, Any
from symfluence.models.base import AutoGeneratedConfigAdapter
from symfluence.core.config.models.model_configs import HydroGeoSphereConfig


class HGSConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for HGS with auto-generated defaults and transformers.

    Defaults and transformers are automatically extracted from HydroGeoSphereConfig
    Pydantic model. Custom validation checks HGS-specific constraints.
    """

    def __init__(self, model_name: str = 'HYDROGEOSPHERE'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return HGS Pydantic configuration schema."""
        return HydroGeoSphereConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate HGS-specific configuration."""
        porosity = config.get('porosity', 0.4)
        if porosity <= 0 or porosity > 1.0:
            raise ValueError(
                f"HGS porosity ({porosity}) must be between 0 and 1."
            )

        vg_n = config.get('vg_n', 2.0)
        if vg_n <= 1.0:
            raise ValueError(
                f"HGS van Genuchten n ({vg_n}) must be greater than 1.0."
            )

        vg_sres = config.get('vg_sres', 0.05)
        if vg_sres < 0 or vg_sres >= 1.0:
            raise ValueError(
                f"HGS residual saturation ({vg_sres}) must be between 0 and 1."
            )
