# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""CWatM Model Configuration."""
from __future__ import annotations

from typing import Any, Dict

from symfluence.core.modeling.base import AutoGeneratedConfigAdapter

from .config_schema import CWatMConfig


class CWatMConfigAdapter(AutoGeneratedConfigAdapter):
    """Configuration adapter for the CWatM model."""

    def __init__(self, model_name: str = 'CWATM'):
        super().__init__(model_name)

    def get_config_schema(self):
        return CWatMConfig

    def validate(self, config: Dict[str, Any]) -> None:
        config_file = config.get('config_file', 'settings.ini')
        if not config_file.endswith('.ini'):
            raise ValueError(
                f"CWatM config_file must be a .ini file, got '{config_file}'"
            )
