# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""PCR-GLOBWB Model Configuration."""
from __future__ import annotations

from typing import Any, Dict

from symfluence.models.base import AutoGeneratedConfigAdapter

from .config_schema import PCRGLOBWBConfig


class PCRGLOBWBConfigAdapter(AutoGeneratedConfigAdapter):
    """Configuration adapter for the PCR-GLOBWB model."""

    def __init__(self, model_name: str = 'PCRGLOBWB'):
        super().__init__(model_name)

    def get_config_schema(self):
        return PCRGLOBWBConfig

    def validate(self, config: Dict[str, Any]) -> None:
        config_file = config.get('config_file', 'setup.ini')
        if not config_file.endswith('.ini'):
            raise ValueError(
                f"PCR-GLOBWB config_file must be a .ini file, got '{config_file}'"
            )
        resolution = config.get('resolution', '05min')
        if resolution not in ('05min', '30min'):
            raise ValueError(
                f"PCR-GLOBWB resolution must be '05min' or '30min', got '{resolution}'"
            )
