"""
SWAT Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the SWAT model.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations in SWATConfig.
"""

from typing import Dict, Any
from symfluence.models.base import AutoGeneratedConfigAdapter
from symfluence.core.config.models.model_configs import SWATConfig


class SWATConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for SWAT model with auto-generated defaults and transformers.

    Defaults and transformers are automatically extracted from SWATConfig
    Pydantic model. Custom validation checks SWAT-specific constraints.
    """

    def __init__(self, model_name: str = 'SWAT'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return SWAT Pydantic configuration schema."""
        return SWATConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate SWAT-specific configuration."""
        # Validate warmup years
        warmup_years = config.get('warmup_years', 2)
        if warmup_years < 0 or warmup_years > 10:
            raise ValueError(
                f"SWAT warmup_years must be 0-10, got {warmup_years}"
            )

        # Validate spatial mode
        spatial_mode = config.get('spatial_mode', 'lumped')
        if spatial_mode not in ('lumped', 'distributed', 'semi_distributed'):
            raise ValueError(
                f"Invalid SWAT spatial_mode '{spatial_mode}'. "
                f"Must be 'lumped', 'distributed', or 'semi_distributed'."
            )

        # Validate TxtInOut directory name is not empty
        txtinout_dir = config.get('txtinout_dir', 'TxtInOut')
        if not txtinout_dir or not txtinout_dir.strip():
            raise ValueError("SWAT txtinout_dir must not be empty.")
