version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Only install documentation dependencies, NOT the full package
# The package has native dependencies (GDAL) that aren't available on RTD
# Autodoc uses mocks configured in conf.py for all heavy imports
python:
  install:
    - requirements: docs/requirements.txt
