# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""Noah-MP Model Configuration."""
from __future__ import annotations

from typing import Any, Dict

from symfluence.core.modeling.base import AutoGeneratedConfigAdapter

from .config_schema import NoahMPConfig


class NoahMPConfigAdapter(AutoGeneratedConfigAdapter):
    """Configuration adapter for the standalone Noah-MP model."""

    def __init__(self, model_name: str = 'NOAHMP'):
        super().__init__(model_name)

    def get_config_schema(self):
        return NoahMPConfig

    def validate(self, config: Dict[str, Any]) -> None:
        namelist = config.get('namelist_file', 'namelist.input')
        if not namelist.endswith('.input'):
            raise ValueError(
                f"Noah-MP namelist_file must be a .input file, got '{namelist}'"
            )
        dt = config.get('timestep', 3600)
        if dt not in (900, 1800, 3600):
            raise ValueError(
                f"Noah-MP timestep must be 900, 1800, or 3600 seconds, got {dt}"
            )
