"""
CLMParFlow Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the ParFlow-CLM tightly-coupled integrated hydrologic model.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations in CLMParFlowConfig.
"""

from typing import Dict, Any
from symfluence.models.base import AutoGeneratedConfigAdapter
from symfluence.core.config.models.model_configs import CLMParFlowConfig


class CLMParFlowConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for CLMParFlow with auto-generated defaults and transformers.

    Defaults and transformers are automatically extracted from CLMParFlowConfig
    Pydantic model. Custom validation checks CLMParFlow-specific constraints.
    """

    def __init__(self, model_name: str = 'CLMPARFLOW'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return CLMParFlow Pydantic configuration schema."""
        return CLMParFlowConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate CLMParFlow-specific configuration."""
        top = config.get('top', 2.0)
        bot = config.get('bot', 0.0)
        if top <= bot:
            raise ValueError(
                f"CLMParFlow top ({top}) must be greater than bot ({bot}). "
                f"Top is the domain surface elevation, bot is the bottom."
            )

        vg_alpha = config.get('vg_alpha', 1.0)
        if vg_alpha <= 0:
            raise ValueError(
                f"CLMParFlow vg_alpha ({vg_alpha}) must be positive."
            )

        vg_n = config.get('vg_n', 2.0)
        if vg_n <= 1.0:
            raise ValueError(
                f"CLMParFlow vg_n ({vg_n}) must be greater than 1.0."
            )

        s_res = config.get('s_res', 0.1)
        s_sat = config.get('s_sat', 1.0)
        if s_res >= s_sat:
            raise ValueError(
                f"CLMParFlow s_res ({s_res}) must be less than s_sat ({s_sat})."
            )
