# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""
VIC Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the VIC model.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations in VICConfig.
"""

from typing import Any, Dict

from symfluence.core.config.models.model_configs import VICConfig
from symfluence.models.base import AutoGeneratedConfigAdapter


class VICConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for VIC model with auto-generated defaults and transformers.

    Defaults and transformers are automatically extracted from VICConfig
    Pydantic model. Custom validation checks VIC-specific constraints.
    """

    def __init__(self, model_name: str = 'VIC'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return VIC Pydantic configuration schema."""
        return VICConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate VIC-specific configuration."""
        # Validate driver type
        driver = config.get('driver', 'image')
        if driver not in ('image', 'classic'):
            raise ValueError(
                f"Invalid VIC driver '{driver}'. Must be 'image' or 'classic'."
            )

        # Validate snow band settings
        snow_band = config.get('snow_band', False)
        n_snow_bands = config.get('n_snow_bands', 10)
        if snow_band and (n_snow_bands < 1 or n_snow_bands > 25):
            raise ValueError(
                f"VIC n_snow_bands must be 1-25, got {n_snow_bands}"
            )
