# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""
MODFLOW 6 Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the MODFLOW 6 groundwater model.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations in MODFLOWConfig.
"""

from typing import Any, Dict

from symfluence.core.config.models.model_configs import MODFLOWConfig
from symfluence.models.base import AutoGeneratedConfigAdapter


class MODFLOWConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for MODFLOW 6 with auto-generated defaults and transformers.

    Defaults and transformers are automatically extracted from MODFLOWConfig
    Pydantic model. Custom validation checks MODFLOW-specific constraints.
    """

    def __init__(self, model_name: str = 'MODFLOW'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return MODFLOW Pydantic configuration schema."""
        return MODFLOWConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate MODFLOW-specific configuration."""
        top = config.get('top', 1500.0)
        bot = config.get('bot', 1400.0)
        if top <= bot:
            raise ValueError(
                f"MODFLOW top ({top}) must be greater than bot ({bot}). "
                f"Top is the aquifer top elevation, bot is the bottom."
            )

        drain_elev = config.get('drain_elevation')
        if drain_elev is not None:
            if drain_elev < bot or drain_elev > top:
                raise ValueError(
                    f"MODFLOW drain_elevation ({drain_elev}) must be between "
                    f"bot ({bot}) and top ({top})."
                )

        grid_type = config.get('grid_type', 'dis')
        if grid_type not in ('dis', 'disv', 'disu'):
            raise ValueError(
                f"MODFLOW grid_type must be 'dis', 'disv', or 'disu', got '{grid_type}'"
            )
