"""
WRF-Hydro Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the WRF-Hydro model.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations in WRFHydroConfig.
"""

from typing import Dict, Any
from symfluence.models.base import AutoGeneratedConfigAdapter
from symfluence.core.config.models.model_configs import WRFHydroConfig


class WRFHydroConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for WRF-Hydro model with auto-generated defaults
    and transformers.

    Defaults and transformers are automatically extracted from WRFHydroConfig
    Pydantic model. Custom validation checks WRF-Hydro-specific constraints.
    """

    def __init__(self, model_name: str = 'WRFHYDRO'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return WRF-Hydro Pydantic configuration schema."""
        return WRFHydroConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate WRF-Hydro-specific configuration."""
        # Validate LSM type
        lsm = config.get('lsm', 'noahmp')
        if lsm not in ('noahmp',):
            raise ValueError(
                f"Invalid WRF-Hydro LSM '{lsm}'. Currently only 'noahmp' is supported."
            )

        # Validate routing option
        routing = config.get('routing_option', 'gridded')
        if routing not in ('gridded', 'reach'):
            raise ValueError(
                f"Invalid routing_option '{routing}'. Must be 'gridded' or 'reach'."
            )

        # Validate channel routing
        channel = config.get('channel_routing', 'diffusive_wave')
        if channel not in ('diffusive_wave', 'muskingum_cunge'):
            raise ValueError(
                f"Invalid channel_routing '{channel}'. "
                f"Must be 'diffusive_wave' or 'muskingum_cunge'."
            )
