"""
mHM Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the mHM model.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations in MHMConfig.
"""

from typing import Dict, Any
from symfluence.models.base import AutoGeneratedConfigAdapter
from symfluence.core.config.models.model_configs import MHMConfig


class MHMConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for mHM model with auto-generated defaults and transformers.

    Defaults and transformers are automatically extracted from MHMConfig
    Pydantic model. Custom validation checks mHM-specific constraints.
    """

    def __init__(self, model_name: str = 'MHM'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return mHM Pydantic configuration schema."""
        return MHMConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate mHM-specific configuration."""
        # Validate namelist file extension
        namelist_file = config.get('namelist_file', 'mhm.nml')
        if not namelist_file.endswith('.nml'):
            raise ValueError(
                f"Invalid mHM namelist file '{namelist_file}'. "
                "Must have .nml extension."
            )

        # Validate routing namelist extension
        routing_namelist = config.get('routing_namelist', 'mrm.nml')
        if not routing_namelist.endswith('.nml'):
            raise ValueError(
                f"Invalid mHM routing namelist '{routing_namelist}'. "
                "Must have .nml extension."
            )

        # Validate timeout range
        timeout = config.get('timeout', 3600)
        if timeout < 60 or timeout > 86400:
            raise ValueError(
                f"mHM timeout must be between 60 and 86400 seconds, got {timeout}"
            )
