# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""LISFLOOD Model Configuration."""
from __future__ import annotations

from typing import Any, Dict

from symfluence.core.config.models.model_configs import LisfloodConfig
from symfluence.models.base import AutoGeneratedConfigAdapter


class LisfloodConfigAdapter(AutoGeneratedConfigAdapter):
    """Configuration adapter for LISFLOOD model."""

    def __init__(self, model_name: str = "LISFLOOD"):
        super().__init__(model_name)

    def get_config_schema(self):
        return LisfloodConfig

    def validate(self, config: Dict[str, Any]) -> None:
        settings_file = config.get("settings_file", "settings.xml")
        if not settings_file.endswith(".xml"):
            raise ValueError(f"LISFLOOD settings_file must be an .xml file, got '{settings_file}'")
