# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""
WATFLOOD Model Configuration.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations in WATFLOODConfig.
"""
from __future__ import annotations

from typing import Any, Dict

from symfluence.core.modeling.base import AutoGeneratedConfigAdapter

from .config_schema import WATFLOODConfig


class WATFLOODConfigAdapter(AutoGeneratedConfigAdapter):
    """Configuration adapter for WATFLOOD model."""

    def __init__(self, model_name: str = 'WATFLOOD'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return WATFLOOD Pydantic configuration schema."""
        return WATFLOODConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate WATFLOOD-specific configuration."""
        pass
