"""
WATFLOOD Model Configuration.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations in WATFLOODConfig.
"""

from typing import Dict, Any
from symfluence.models.base import AutoGeneratedConfigAdapter
from symfluence.core.config.models.model_configs import WATFLOODConfig


class WATFLOODConfigAdapter(AutoGeneratedConfigAdapter):
    """Configuration adapter for WATFLOOD model."""

    def __init__(self, model_name: str = 'WATFLOOD'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return WATFLOOD Pydantic configuration schema."""
        return WATFLOODConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate WATFLOOD-specific configuration."""
        pass
