"""
CRHM Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the CRHM model.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations in CRHMConfig.
"""

from typing import Dict, Any
from symfluence.models.base import AutoGeneratedConfigAdapter
from symfluence.core.config.models.model_configs import CRHMConfig


class CRHMConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for CRHM model with auto-generated defaults and transformers.

    Defaults and transformers are automatically extracted from CRHMConfig
    Pydantic model. Custom validation checks CRHM-specific constraints.
    """

    def __init__(self, model_name: str = 'CRHM'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return CRHM Pydantic configuration schema."""
        return CRHMConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate CRHM-specific configuration."""
        # Validate spatial mode
        spatial_mode = config.get('spatial_mode', 'lumped')
        if spatial_mode not in ('lumped', 'distributed'):
            raise ValueError(
                f"Invalid CRHM spatial_mode '{spatial_mode}'. "
                f"Must be 'lumped' or 'distributed'."
            )

        # Validate project file extension
        project_file = config.get('project_file', 'model.prj')
        if not project_file.endswith('.prj'):
            raise ValueError(
                f"CRHM project file must have .prj extension, got '{project_file}'"
            )

        # Validate observation file extension
        obs_file = config.get('observation_file', 'forcing.obs')
        if not obs_file.endswith('.obs'):
            raise ValueError(
                f"CRHM observation file must have .obs extension, got '{obs_file}'"
            )
