"""
CLM Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the CLM (Community Land Model / CTSM 5.x) model.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations in CLMConfig.
"""

from typing import Any, Dict

from symfluence.core.config.models.model_configs import CLMConfig
from symfluence.models.base import AutoGeneratedConfigAdapter


class CLMConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for CLM model with auto-generated defaults and transformers.

    Defaults and transformers are automatically extracted from CLMConfig
    Pydantic model. Custom validation checks CLM-specific constraints.
    """

    def __init__(self, model_name: str = 'CLM'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return CLM Pydantic configuration schema."""
        return CLMConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate CLM-specific configuration."""
        hist_nhtfrq = config.get('hist_nhtfrq', -24)
        if hist_nhtfrq > 0 and hist_nhtfrq > 48:
            raise ValueError(
                f"CLM hist_nhtfrq={hist_nhtfrq} is too large. "
                f"Use negative values for hourly output (e.g., -24 = daily)."
            )
