"""
MIKE-SHE Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the MIKE-SHE (DHI) model.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations in MIKESHEConfig.
"""

from typing import Dict, Any
from symfluence.models.base import AutoGeneratedConfigAdapter
from symfluence.core.config.models.model_configs import MIKESHEConfig


class MIKESHEConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for MIKE-SHE model with auto-generated defaults
    and transformers.

    Defaults and transformers are automatically extracted from MIKESHEConfig
    Pydantic model. Custom validation checks MIKE-SHE-specific constraints.
    """

    def __init__(self, model_name: str = 'MIKESHE'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return MIKE-SHE Pydantic configuration schema."""
        return MIKESHEConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate MIKE-SHE-specific configuration."""
        # Validate setup file extension
        setup_file = config.get('setup_file', 'model.she')
        if not setup_file.endswith('.she'):
            raise ValueError(
                f"Invalid MIKE-SHE setup file '{setup_file}'. "
                f"Must have '.she' extension."
            )

        # Validate timeout range
        timeout = config.get('timeout', 7200)
        if timeout < 60 or timeout > 86400:
            raise ValueError(
                f"MIKE-SHE timeout must be 60-86400 seconds, got {timeout}"
            )
