"""
Ngen Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the NextGen Framework model.

This module registers Ngen-specific configuration components with the
ModelRegistry, enabling the core config system to remain model-agnostic.

PHASE 2 REFACTORING: This adapter now uses AutoGeneratedConfigAdapter
to auto-generate defaults and transformers from Pydantic Field declarations.
All defaults are maintained in NgenConfig (model_configs.py) for single
source of truth.
"""

from typing import Dict, Any
from symfluence.models.base import AutoGeneratedConfigAdapter, ConfigValidationError
from symfluence.core.config.models.model_configs import NGENConfig


class NgenConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for NGEN model with auto-generated defaults and transformers.

    Defaults and transformers are automatically extracted from NGENConfig
    Pydantic model. Only custom validation logic is implemented here.
    """

    def __init__(self, model_name: str = 'NGEN'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return NGEN Pydantic configuration schema."""
        return NGENConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate Ngen-specific configuration."""
        pass  # Add custom validation logic if needed


# Backward compatibility alias
NGENConfigAdapter = NgenConfigAdapter
