"""Wflow Model Configuration."""
from typing import Any, Dict

from symfluence.core.config.models.model_configs import WflowConfig
from symfluence.models.base import AutoGeneratedConfigAdapter


class WflowConfigAdapter(AutoGeneratedConfigAdapter):
    """Configuration adapter for Wflow model."""

    def __init__(self, model_name: str = 'WFLOW'):
        super().__init__(model_name)

    def get_config_schema(self):
        return WflowConfig

    def validate(self, config: Dict[str, Any]) -> None:
        config_file = config.get('config_file', 'wflow_sbm.toml')
        if not config_file.endswith('.toml'):
            raise ValueError(
                f"Wflow config_file must be a .toml file, got '{config_file}'"
            )
