# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""
MizuRoute Control File Writer

Unified control file generation for every source model that declares a runoff
artifact on its registered ``ModelConfigSchema``. Eliminates code duplication
by using configuration-driven templates.
"""
from __future__ import annotations

import logging
from pathlib import Path
from typing import TYPE_CHECKING, Any, Dict, Optional, TextIO, Union

from symfluence.core.exceptions import ConfigurationError, ConfigValidationError
from symfluence.core.mixins import ConfigurableMixin
from symfluence.core.modeling.utilities.runoff_loader import (
    MODEL_CONFIGS,
    ModelRunoffConfig,
    get_model_config,
)

if TYPE_CHECKING:
    from symfluence.core.config.models import SymfluenceConfig

# ``MODEL_CONFIGS`` / ``ModelRunoffConfig`` are re-exported for the callers that
# used to import them from here. The values themselves are no longer declared
# in this module: each model declares its runoff artifact on its registered
# ModelConfigSchema and ``get_model_config`` serves it. The local copy this
# replaces held the same values for SUMMA/FUSE/GR/NGEN, so collapsing onto the
# declaration changed nothing here — the four routable sources are the same
# four. (It also omitted HYPE, which read as a gap at the time; HYPE has since
# been established as not routable at all, so the omission was right.)
__all__ = ['MODEL_CONFIGS', 'ModelRunoffConfig', 'ControlFileWriter']


class ControlFileWriter(ConfigurableMixin):
    """
    Unified mizuRoute control file writer.

    Handles control file generation for any source model with a registered
    runoff declaration, using a template-based approach with model-specific
    configurations served by ``runoff_loader.get_model_config``.
    """

    def __init__(
        self,
        config: Union['SymfluenceConfig', Dict[str, Any]],
        setup_dir: Path,
        project_dir: Path,
        experiment_id: str,
        domain_name: str,
        logger: Optional[logging.Logger] = None
    ):
        # Set up typed config via ConfigurableMixin
        from symfluence.core.config.coercion import coerce_config
        self._config = coerce_config(config, warn=False)
        # Backward compatibility alias
        self.config = self._config

        self.setup_dir = setup_dir
        self.project_dir = project_dir
        self.experiment_id = experiment_id
        self.domain_name = domain_name
        self.logger = logger or logging.getLogger(__name__)

        # These can be set by the preprocessor before writing
        self.summa_uses_gru_runoff = False
        self.needs_remap_lumped_distributed = False

    def write_control_file(
        self,
        model_type: str = 'summa',
        control_file_name: Optional[str] = None,
        mizu_config: Optional[Dict[str, Any]] = None
    ) -> Path:
        """
        Write a mizuRoute control file for the specified source model.

        Args:
            model_type: Source model type ('summa', 'fuse', 'gr', 'ngen',
                'hype', ... — any model with a registered runoff declaration)
            control_file_name: Override control file name (default from config)
            mizu_config: MizuRoute-specific config values (topology file, remap file, etc.)

        Returns:
            Path to the generated control file
        """
        model_type = model_type.lower()
        try:
            model_config = get_model_config(model_type)
        except ConfigurationError as exc:
            raise ConfigValidationError(
                f"Unknown model type: {model_type}. Expected one of: "
                f"{sorted(MODEL_CONFIGS)}"
            ) from exc

        mizu_config = mizu_config or {}

        # Determine control file name
        if control_file_name is None:
            default_name = 'mizuroute.control' if model_type != 'gr' else 'mizuRoute_control_GR.txt'
            control_file_name = self._get_config_value(lambda: self.config.model.mizuroute.control_file, default=default_name)

        control_path = self.setup_dir / control_file_name
        self.logger.debug(f"Creating mizuRoute control file for {model_type.upper()}: {control_path}")

        with open(control_path, 'w', encoding='utf-8') as cf:
            self._write_header(cf)
            self._write_directories(cf, model_config)
            self._write_parameters(cf, mizu_config)
            self._write_simulation_controls(cf, model_type)
            self._write_topology(cf, mizu_config)
            self._write_runoff(cf, model_config)
            self._write_remapping(cf, mizu_config)
            self._write_miscellaneous(cf, mizu_config)

        self.logger.debug(f"mizuRoute control file created: {control_path}")
        return control_path

    def _write_header(self, cf: TextIO) -> None:
        """Write control file header."""
        cf.write("! mizuRoute control file generated by SUMMA public workflow scripts \n")

    def _get_model_experiment_output(self, model_config: ModelRunoffConfig) -> str:
        """Get experiment output path for a specific model type."""
        # Map model output_dir_key to typed config path
        key_to_config = {
            'EXPERIMENT_OUTPUT_SUMMA': lambda: self.config.model.summa.experiment_output,
            'EXPERIMENT_OUTPUT_FUSE': lambda: self.config.model.fuse.experiment_output,
            'EXPERIMENT_OUTPUT_GR': lambda: self.config.model.gr.experiment_output,
            'EXPERIMENT_OUTPUT_NGEN': lambda: self.config.model.ngen.experiment_output if self.config.model.ngen else None,
            # No HYPE entry: it is not a routable source, so no HYPE runoff
            # declaration exists to carry EXPERIMENT_OUTPUT_HYPE as its
            # output_dir_key and this map is never asked for it.
        }
        getter = key_to_config.get(model_config.output_dir_key)
        if getter:
            return self._get_config_value(getter, default='default')
        return 'default'

    def _write_directories(self, cf: TextIO, model_config: ModelRunoffConfig) -> None:
        """Write directory paths section."""
        # Get model-specific output directory
        model_output = self._get_model_experiment_output(model_config)
        if model_output == 'default':
            model_output = self.project_dir / f"simulations/{self.experiment_id}" / model_config.output_dir_name
        else:
            model_output = Path(model_output)

        # Get mizuRoute output directory
        mizu_output = self._get_config_value(lambda: self.config.model.mizuroute.experiment_output, default='default')
        if mizu_output == 'default' or not mizu_output:
            mizu_output = self.project_dir / f"simulations/{self.experiment_id}" / 'mizuRoute'
        else:
            mizu_output = Path(mizu_output)

        # Ensure output directory exists
        mizu_output.mkdir(parents=True, exist_ok=True)

        cf.write("!\n! --- DEFINE DIRECTORIES \n")
        cf.write(f"<ancil_dir>             {self.setup_dir}/    ! Folder that contains ancillary data (river network, remapping netCDF) \n")
        cf.write(f"<input_dir>             {model_output}/    ! Folder that contains runoff data from {model_config.comment_name} \n")
        cf.write(f"<output_dir>            {mizu_output}/    ! Folder that will contain mizuRoute simulations \n")

    def _write_parameters(self, cf: TextIO, mizu_config: Dict[str, Any]) -> None:
        """Write namelist parameters section."""
        param_file = mizu_config.get('parameters_file', self._get_config_value(lambda: self.config.model.mizuroute.parameter_file, default='mizuRoute_params.nml'))
        cf.write("!\n! --- NAMELIST FILENAME \n")
        cf.write(f"<param_nml>             {param_file}    ! Spatially constant parameter namelist (should be stored in the ancil_dir) \n")

    def _write_simulation_controls(self, cf: TextIO, model_type: str) -> None:
        """Write simulation control section with proper time handling."""
        sim_start = self._get_config_value(lambda: self.config.domain.time_start, default='')
        sim_end = self._get_config_value(lambda: self.config.domain.time_end, default='')

        # Special handling for GR: force midnight alignment for daily data
        if model_type == 'gr':
            if isinstance(sim_start, str):
                sim_start = sim_start.split(' ')[0] + " 00:00:00"
            if isinstance(sim_end, str):
                sim_end = sim_end.split(' ')[0] + " 00:00:00"
            self.logger.debug(f"Forced GR simulation period to midnight: {sim_start} to {sim_end}")

        # Ensure dates are in proper format with seconds (mizuRoute requires HH:MM:SS)
        if isinstance(sim_start, str):
            if len(sim_start) == 10:  # Date only: YYYY-MM-DD
                sim_start = f"{sim_start} 00:00:00"
            elif len(sim_start) == 16:  # Date + time without seconds: YYYY-MM-DD HH:MM
                sim_start = f"{sim_start}:00"
        if isinstance(sim_end, str):
            if len(sim_end) == 10:  # Date only: YYYY-MM-DD
                sim_end = f"{sim_end} 23:00:00"
            elif len(sim_end) == 16:  # Date + time without seconds: YYYY-MM-DD HH:MM
                sim_end = f"{sim_end}:00"

        # Get routing scheme from config (default to IRF for proper river routing)
        route_opt = self._get_config_value(
            lambda: self.config.model.mizuroute.output_vars,
            default='1',
            dict_key='SETTINGS_MIZU_OUTPUT_VARS'
        )

        # Get output file frequency from config
        output_freq = self._get_config_value(
            lambda: self.config.model.mizuroute.output_freq,
            default='yearly',
            dict_key='SETTINGS_MIZU_OUTPUT_FREQ'
        )

        cf.write("!\n! --- DEFINE SIMULATION CONTROLS \n")
        cf.write(f"<case_name>             {self.experiment_id}    ! Simulation case name \n")
        cf.write(f"<sim_start>             {sim_start}    ! Time of simulation start \n")
        cf.write(f"<sim_end>               {sim_end}    ! Time of simulation end \n")
        cf.write(f"<route_opt>             {route_opt}    ! Routing scheme. 0 -> accumRunoff, 1 -> IRF-UH, 2 -> IRF-KW, 3 -> KW-IRF, 4 -> MC-IRF \n")
        cf.write(f"<newFileFrequency>      {output_freq}    ! Output file frequency (single, yearly, monthly, daily) \n")

    def _write_topology(self, cf: TextIO, mizu_config: Dict[str, Any]) -> None:
        """Write topology file section."""
        topology_file = mizu_config.get('topology_file', self._get_config_value(lambda: self.config.model.mizuroute.topology_file, default='network_topology.nc'))

        cf.write("!\n! --- DEFINE TOPOLOGY FILE \n")
        cf.write(f"<fname_ntopOld>         {topology_file}    ! Name of input netCDF for River Network \n")
        cf.write("<dname_sseg>            seg    ! Dimension name for reach in river network netCDF \n")
        cf.write("<dname_nhru>            hru    ! Dimension name for RN_HRU in river network netCDF \n")
        cf.write("<seg_outlet>            -9999    ! Outlet reach ID at which to stop routing (i.e. use subset of full network). -9999 to use full network \n")
        cf.write("<varname_area>          area    ! Name of variable holding hru area \n")
        cf.write("<varname_length>        length    ! Name of variable holding segment length \n")
        cf.write("<varname_slope>         slope    ! Name of variable holding segment slope \n")
        cf.write("<varname_HRUid>         hruId    ! Name of variable holding HRU id \n")
        cf.write("<varname_hruSegId>      hruToSegId    ! Name of variable holding the stream segment below each HRU \n")
        cf.write("<varname_segId>         segId    ! Name of variable holding the ID of each stream segment \n")
        cf.write("<varname_downSegId>     downSegId    ! Name of variable holding the ID of the next downstream segment \n")

    def _write_runoff(self, cf: TextIO, model_config: ModelRunoffConfig) -> None:
        """Write runoff file section with model-specific settings."""
        # Get overrideable values from config
        routing_var = self._get_config_value(lambda: self.config.model.mizuroute.routing_var, default=model_config.default_var)
        if routing_var in ('default', None, ''):
            routing_var = model_config.default_var
        elif routing_var == 'averageRoutedRunoff' and model_config.default_var != 'averageRoutedRunoff':
            routing_var = model_config.default_var

        routing_units = self._get_config_value(lambda: self.config.model.mizuroute.routing_units, default=model_config.default_units)
        if routing_units in ('default', None, ''):
            routing_units = model_config.default_units

        routing_dt = self._get_config_value(lambda: self.config.model.mizuroute.routing_dt, default=model_config.default_dt)
        if routing_dt in ('default', None, ''):
            routing_dt = model_config.default_dt

        # For FUSE, dt_qsim must match the actual FUSE output timestep,
        # not the generic SETTINGS_MIZU_ROUTING_DT which is for routing computation.
        # FUSE always outputs daily data — the generic routing_dt (often 3600 for
        # SUMMA) must not override this.
        if model_config.comment_name == 'FUSE':
            routing_dt = model_config.default_dt  # 86400 (daily)

        # Generate output file name from pattern.
        # FUSE truncates FMODEL_ID to 6 chars, hashing if longer — the
        # mizuRoute control file must match the actual FUSE output name.
        eid = self.experiment_id
        if model_config.comment_name == 'FUSE' and len(eid) > 6:
            import hashlib
            eid = hashlib.md5(eid.encode(), usedforsecurity=False).hexdigest()[:6]
        output_file = model_config.output_file_pattern.format(
            experiment_id=eid,
            domain_name=self.domain_name
        )

        # Self-heal a stale/incorrect runoff variable name (analogous to the FUSE
        # path, PR #69). A config carrying a FUSE-style 'q_routed' in a SUMMA run
        # otherwise produces a control file mizuRoute cannot read ("Variable not
        # found"). When the model output already exists — routing runs after the
        # model — detect the variable that is actually present and override.
        detected_var = self._detect_runoff_variable(model_config, routing_var)
        if detected_var and detected_var != routing_var:
            self.logger.warning(
                f"mizuRoute control: configured runoff variable '{routing_var}' not found in "
                f"{model_config.comment_name} output; using detected variable '{detected_var}'. "
                f"Resetting runoff units/dt to {model_config.comment_name} defaults "
                f"('{model_config.default_units}', {model_config.default_dt}s)."
            )
            routing_var = detected_var
            # The configured variable name was wrong for this model, so any units/dt
            # overrides alongside it are equally untrustworthy — fall back to the
            # model's known-good defaults to avoid a silent magnitude error.
            routing_units = model_config.default_units
            routing_dt = model_config.default_dt

        # Determine HRU dimension/variable (can be overridden for distributed SUMMA)
        hru_dim = model_config.hru_dim
        hru_var = model_config.hru_var
        if self.summa_uses_gru_runoff and model_config.hru_dim == 'hru':
            hru_dim = 'gru'
            hru_var = 'gruId'

        cf.write("!\n! --- DEFINE RUNOFF FILE \n")
        cf.write(f"<fname_qsim>            {output_file}    ! netCDF name for {model_config.comment_name} runoff \n")
        cf.write(f"<vname_qsim>            {routing_var}    ! Variable name for {model_config.comment_name} runoff \n")
        cf.write(f"<units_qsim>            {routing_units}    ! Units of input runoff \n")
        cf.write(f"<dt_qsim>               {routing_dt}    ! Time interval of input runoff in seconds \n")
        cf.write("<dname_time>            time    ! Dimension name for time \n")
        cf.write("<vname_time>            time    ! Variable name for time \n")
        cf.write(f"<dname_hruid>           {hru_dim}     ! Dimension name for HM_HRU ID \n")
        cf.write(f"<vname_hruid>           {hru_var}   ! Variable name for HM_HRU ID \n")
        cf.write("<calendar>              standard    ! Calendar of the nc file \n")

    def _detect_runoff_variable(self, model_config: ModelRunoffConfig, configured_var: str) -> Optional[str]:
        """Return the runoff variable actually present in the model output file.

        Inspects the source model's runoff NetCDF and reconciles it with the
        configured ``SETTINGS_MIZU_ROUTING_VAR``. This is the SUMMA-side analogue
        of the FUSE runner's variable self-healing (PR #69).

        Returns:
            - ``configured_var`` if it exists in the output (respect user config),
            - a detected variable name if ``configured_var`` is absent,
            - ``None`` if the output file is unavailable — e.g. the control file is
              written during preprocessing, before the model has run — in which
              case the caller keeps the configured value.
        """
        try:
            from symfluence.core.modeling.utilities.runoff_loader import (
                detect_runoff_variable,
                resolve_runoff_file,
            )

            # output_dir_name ('SUMMA'/'FUSE'/'GR'/'NGEN') is the canonical source
            # key understood by both resolve_runoff_file and detect_runoff_variable.
            source_model = model_config.output_dir_name
            runoff_file = resolve_runoff_file(
                source_model=source_model,
                project_dir=self.project_dir,
                experiment_id=self.experiment_id,
                domain_name=self.domain_name,
                config=self.config,
            )
            if not runoff_file or not runoff_file.exists():
                return None

            import xarray as xr
            with xr.open_dataset(runoff_file, decode_times=False) as ds:
                if configured_var in ds.data_vars:
                    return configured_var
                return detect_runoff_variable(ds, source_model=source_model)
        except Exception as e:  # noqa: BLE001 — detection is best-effort; keep config on failure
            self.logger.debug(f"Runoff variable auto-detection skipped: {e}")
            return None

    def _write_remapping(self, cf: TextIO, mizu_config: Dict[str, Any]) -> None:
        """Write runoff remapping section."""
        remap_file = mizu_config.get('remap_file', self._get_config_value(lambda: self.config.model.mizuroute.remap_file, default='runoff_remap.nc'))
        remap_flag = (
            self._get_config_value(lambda: self.config.model.mizuroute.needs_remap, default=False) or
            self.needs_remap_lumped_distributed
        )

        cf.write("!\n! --- DEFINE RUNOFF MAPPING FILE \n")
        cf.write(f"<is_remap>              {'T' if remap_flag else 'F'}    ! Logical to indicate runoff needs to be remapped to RN_HRU. T or F \n")

        if remap_flag:
            cf.write(f"<fname_remap>           {remap_file}    ! netCDF name of runoff remapping \n")
            cf.write("<vname_hruid_in_remap>  RN_hruId    ! Variable name for RN_HRUs \n")
            cf.write("<vname_weight>          weight    ! Variable name for areal weights of overlapping HM_HRUs \n")
            cf.write("<vname_qhruid>          HM_hruId    ! Variable name for HM_HRU ID \n")
            cf.write("<vname_num_qhru>        nOverlaps    ! Variable name for a numbers of overlapping HM_HRUs with RN_HRUs \n")
            cf.write("<dname_hru_remap>       hru    ! Dimension name for HM_HRU \n")
            cf.write("<dname_data_remap>      data    ! Dimension name for data \n")

    def _write_miscellaneous(self, cf: TextIO, mizu_config: Dict[str, Any]) -> None:
        """Write miscellaneous settings section."""
        within_basin = mizu_config.get('within_basin', self._get_config_value(lambda: self.config.model.mizuroute.within_basin, default=0))
        cf.write("!\n! --- MISCELLANEOUS \n")
        cf.write(f"<doesBasinRoute>        {within_basin}    ! Hillslope routing options. 0 -> no (already routed by SUMMA), 1 -> use IRF \n")
