#!/usr/bin/env python3
"""
Fail CI if a resilience broad-except handler logs a failure without a traceback.

Theme B / review item 10: handlers tagged ``# noqa: BLE001 — {model execution,
calibration, preprocessing} resilience`` must record a traceback when they log,
i.e. the logging call carries ``exc_info=True`` (or uses ``logger.exception``).
Otherwise the diagnostic detail is lost — "a failed calibration run silently
loses its traceback."

A handler is FLAGGED when it contains at least one ``logger.<level>(...)`` call
(error/warning/info/debug/critical) and **none** of its logging calls capture a
traceback (no ``exc_info`` keyword and no ``logger.exception``). Silent handlers
(no logging) are not flagged.

Comparison is against a checked-in allowlist (same ``path:context:source`` scheme
as check_broad_exceptions.py), so residual/edge cases are grandfathered while new
regressions fail CI.
"""

from __future__ import annotations

import argparse
import ast
import sys
from collections import Counter
from pathlib import Path
from typing import List, Tuple

DEFAULT_SCAN_ROOT = Path("src/symfluence")
DEFAULT_ALLOWLIST = Path("tools/quality/resilience_logging_allowlist.txt")
MODULE_SCOPE = "<module>"
CATEGORIES = ("model execution resilience", "calibration resilience", "preprocessing resilience")
LOG_LEVELS = {"error", "warning", "info", "debug", "critical"}


def _is_resilience_handler(handler: ast.ExceptHandler, source_lines: List[str]) -> bool:
    """True if the except line carries a `# noqa: BLE001 — <cat> resilience` tag."""
    line = source_lines[handler.lineno - 1] if 1 <= handler.lineno <= len(source_lines) else ""
    return "BLE001" in line and any(cat in line for cat in CATEGORIES)


def _logging_calls(handler: ast.ExceptHandler) -> Tuple[list, bool]:
    """Return (level_calls, captures_traceback) for logger calls in the handler body."""
    level_calls = []
    captures = False
    for node in ast.walk(handler):
        if not (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)):
            continue
        attr = node.func.attr
        try:
            receiver = ast.unparse(node.func.value)
        except Exception:  # noqa: BLE001 - unparse is best-effort
            receiver = ""
        if not (receiver.endswith("logger") or receiver.endswith("log") or receiver == "logging"):
            continue
        if attr == "exception":
            captures = True
        elif attr in LOG_LEVELS:
            level_calls.append(node)
            if any(kw.arg == "exc_info" for kw in node.keywords):
                captures = True
    return level_calls, captures


def _qualified_context(stack: List[str]) -> str:
    return ".".join(stack) if stack else MODULE_SCOPE


def _walk(tree: ast.AST, source_lines: List[str]) -> List[Tuple[str, str]]:
    matches: List[Tuple[str, str]] = []

    def _visit(node: ast.AST, stack: List[str]) -> None:
        new_stack = stack + [node.name] if isinstance(
            node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)
        ) else stack
        if isinstance(node, ast.ExceptHandler) and _is_resilience_handler(node, source_lines):
            level_calls, captures = _logging_calls(node)
            if level_calls and not captures:
                src = source_lines[node.lineno - 1].strip() if node.lineno <= len(source_lines) else ""
                matches.append((_qualified_context(stack), src))
        for child in ast.iter_child_nodes(node):
            _visit(child, new_stack)

    for child in ast.iter_child_nodes(tree):
        _visit(child, [])
    return matches


def collect_matches(scan_root: Path) -> list[str]:
    records: list[str] = []
    for path in sorted(scan_root.rglob("*.py")):
        rel = path.as_posix()
        try:
            source = path.read_text(encoding="utf-8")
            tree = ast.parse(source, filename=rel)
        except (OSError, SyntaxError) as exc:
            print(f"warning: could not read/parse {rel}: {exc}", file=sys.stderr)
            continue
        for context, line in _walk(tree, source.splitlines()):
            records.append(f"{rel}:{context}:{line}")
    return sorted(records)


def read_allowlist(path: Path) -> list[str]:
    if not path.exists():
        return []
    return sorted(t for t in (l.strip() for l in path.read_text(encoding="utf-8").splitlines())
                  if t and not t.startswith("#"))


def write_allowlist(path: Path, records: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "# Resilience handlers that log without a traceback — allowlist.",
        "# Auto-generated by scripts/check_resilience_logging.py --update",
        "# Format: relative/path.py:enclosing.scope:source",
        "# New resilience handlers must log with exc_info=True / logger.exception.",
        "",
    ]
    path.write_text("\n".join(header) + "".join(f"{r}\n" for r in records), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--scan-root", type=Path, default=DEFAULT_SCAN_ROOT)
    parser.add_argument("--allowlist", type=Path, default=DEFAULT_ALLOWLIST)
    parser.add_argument("--update", action="store_true")
    args = parser.parse_args()

    current = collect_matches(args.scan_root)
    if args.update:
        write_allowlist(args.allowlist, current)
        print(f"Updated allowlist with {len(current)} entries: {args.allowlist}")
        return 0

    allowed = Counter(read_allowlist(args.allowlist))
    new_items = sorted((Counter(current) - allowed).elements())
    stale = sorted((allowed - Counter(current)).elements())
    if new_items:
        print("Resilience handlers logging without a traceback (not in allowlist):", file=sys.stderr)
        for item in new_items:
            print(f"  {item}", file=sys.stderr)
        print("\nAdd exc_info=True / use logger.exception. To accept:\n"
              "  python scripts/check_resilience_logging.py --update", file=sys.stderr)
        return 1
    print(f"Resilience logging guard passed ({len(current)} allowlisted matches).")
    if stale:
        print(f"Note: {len(stale)} stale allowlist entries detected. Run --update to prune.",
              file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
