# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2024-2026 SYMFLUENCE Team <dev@symfluence.org>

"""
PIHM Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the PIHM (Penn State Integrated Hydrologic Model).

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations in PIHMConfig.
"""

from typing import Any, Dict

from symfluence.core.config.models.model_configs import PIHMConfig
from symfluence.models.base import AutoGeneratedConfigAdapter


class PIHMConfigAdapter(AutoGeneratedConfigAdapter):
    """
    Configuration adapter for PIHM with auto-generated defaults and transformers.

    Defaults and transformers are automatically extracted from PIHMConfig
    Pydantic model. Custom validation checks PIHM-specific constraints.
    """

    def __init__(self, model_name: str = 'PIHM'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return PIHM Pydantic configuration schema."""
        return PIHMConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate PIHM-specific configuration."""
        porosity = config.get('porosity', 0.4)
        if porosity <= 0 or porosity > 1.0:
            raise ValueError(
                f"PIHM porosity ({porosity}) must be between 0 and 1."
            )

        vg_n = config.get('vg_n', 2.0)
        if vg_n <= 1.0:
            raise ValueError(
                f"PIHM van Genuchten n ({vg_n}) must be greater than 1.0."
            )
