"""
T-Route Model Configuration.

Provides configuration schema, defaults, transformers, and validation
for the t-route (NOAA OWP) channel routing model.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations. All defaults are maintained in TRouteConfig
(model_configs.py) for single source of truth.
"""

from typing import Dict, Any
from symfluence.models.base import AutoGeneratedConfigAdapter


class TRouteConfigAdapter(AutoGeneratedConfigAdapter):
    """Configuration adapter for t-route with auto-generated defaults and transformers.

    Defaults and transformers are automatically extracted from TRouteConfig
    Pydantic model. Only custom validation logic is implemented here.
    """

    def __init__(self, model_name: str = 'TROUTE'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return t-route Pydantic configuration schema."""
        from symfluence.core.config.models.model_configs import TRouteConfig
        return TRouteConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate t-route-specific configuration.

        Checks:
        - Routing method is valid
        - Manning's n is positive
        - Timestep within bounds
        """
        routing_method = config.get('routing_method', 'muskingum_cunge')
        valid_methods = ['muskingum_cunge', 'diffusive_wave']
        if routing_method not in valid_methods:
            raise ValueError(
                f"Invalid routing_method '{routing_method}'. "
                f"Must be one of: {valid_methods}"
            )

        mannings_n = config.get('mannings_n', 0.035)
        if mannings_n <= 0:
            raise ValueError(
                f"mannings_n must be positive, got {mannings_n}"
            )

        dt_seconds = config.get('dt_seconds', 3600)
        if not (60 <= dt_seconds <= 86400):
            raise ValueError(
                f"dt_seconds must be between 60 and 86400, got {dt_seconds}"
            )
