"""
GSFLOW Model Configuration.

Uses AutoGeneratedConfigAdapter to auto-generate defaults and transformers
from Pydantic Field declarations in GSFLOWConfig.
"""

from typing import Dict, Any
from symfluence.models.base import AutoGeneratedConfigAdapter
from symfluence.core.config.models.model_configs import GSFLOWConfig


class GSFLOWConfigAdapter(AutoGeneratedConfigAdapter):
    """Configuration adapter for GSFLOW model."""

    def __init__(self, model_name: str = 'GSFLOW'):
        super().__init__(model_name)

    def get_config_schema(self):
        """Return GSFLOW Pydantic configuration schema."""
        return GSFLOWConfig

    def validate(self, config: Dict[str, Any]) -> None:
        """Validate GSFLOW-specific configuration."""
        mode = config.get('gsflow_mode', 'COUPLED')
        if mode not in ('PRMS', 'MODFLOW', 'COUPLED'):
            raise ValueError(
                f"Invalid GSFLOW mode '{mode}'. "
                f"Must be 'PRMS', 'MODFLOW', or 'COUPLED'."
            )
